# permissions for end users to edit composables.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: composable-editor-role
rules:
- apiGroups:
  - ibmcloud.ibm.com
  resources:
  - composables
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ibmcloud.ibm.com
  resources:
  - composables/status
  verbs:
  - get
