name: Release

on:
  push:
    branches:
    - 'master'
    tags:
    - '*'

env:
  IMAGE_NAME: cloudoperators/composable-controller

jobs:
  publish-gh-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Extract Tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}
      - name: Build manifests
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          set -eu -o pipefail
          kustomize build config/default \
            | sed "s#cloudoperators/composable-controller#${{ env.IMAGE_NAME }}:${RELEASE_VERSION}#g" \
            > manifests.yaml
          kustomize build config/crd > crds.yaml
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            manifests.yaml
            crds.yaml

