name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: ['main']


steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-go@v2
    with:
      go-version: '^1.17.8'

  - name: test
    run: |
      make test
